<?php

namespace Slince\Upload;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Throwable;

final class File
{
    /**
     * @var string
     */
    protected string $name;

    /**
     * @var UploadedFile
     */
    protected UploadedFile $uploadedFile;

    /**
     * Is uploaded
     *
     * @var boolean
     */
    protected bool $uploaded;

    /**
     * @var Throwable
     */
    protected Throwable $exception;

    /**
     * Storage system returned.
     *
     * @var \Symfony\Component\HttpFoundation\File\File|mixed
     */
    protected mixed $details;

    public function __construct(UploadedFile $uploadedFile, string $name, bool $uploaded, mixed $details = null, Throwable $exception = null)
    {
        $this->uploadedFile = $uploadedFile;
        $this->name = $name;
        $this->uploaded = $uploaded;
        $this->details = $details;
        $this->exception = $exception;
    }

    /**
     * Gets the key generated by `Namer`
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Access file details saved in client by this object.
     *
     * @return UploadedFile
     */
    public function getUploadedFile(): UploadedFile
    {
        return $this->uploadedFile;
    }

    /**
     * Checks whether the file is uploaded successfully.
     *
     * @return bool
     */
    public function isUploaded(): bool
    {
        return $this->uploaded;
    }

    /**
     * The exception if the file is uploaded error.
     *
     * @return Throwable|null
     */
    public function getException(): ?Throwable
    {
        return $this->exception;
    }

    /**
     * File details provided by storage layer.
     *
     * @return \Symfony\Component\HttpFoundation\File\File|mixed
     */
    public function getDetails(): mixed
    {
        return $this->details;
    }
}
